language: java
jdk:
  - openjdk8
sudo: false
cache:
  directories:
    - "$HOME/.m2"
install:
  - mvn -nsu -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} clean deploy
before_deploy:
  - openssl aes-256-cbc -K $encrypted_a65247dffca0_key -iv $encrypted_a65247dffca0_iv
    -in deploy_rsa.enc -out ./deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - chmod +x scripts/deploy-release.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy-release.sh
    on:
      branch: master
